# Generated by Django 4.2.5 on 2023-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_question_remove_choice_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(to='polls.choice'),
        ),
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
    ]
