# Generated by Django 4.2.5 on 2023-10-02 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_question_users_alter_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='users',
        ),
        migrations.AddField(
            model_name='choice',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
