# Generated by Django 4.2.5 on 2023-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_question_users_choice_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='single_choice',
            field=models.BooleanField(default=True),
        ),
    ]
